"""migration stock IDX

Revision ID: 155690c063a1
Revises: dff1771e47f4
Create Date: 2023-08-10 12:50:42.508720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155690c063a1'
down_revision: Union[str, None] = 'dff1771e47f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('affiliated', sa.Boolean(), nullable=True),
    sa.Column('id_field', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('new_sector_name', sa.String(), nullable=True),
    sa.Column('new_sub_sector_name', sa.String(), nullable=True),
    sa.Column('new_industry_name', sa.String(), nullable=True),
    sa.Column('new_sub_industry_name', sa.String(), nullable=True),
    sa.Column('sector_name', sa.String(), nullable=True),
    sa.Column('sub_sector_name', sa.String(), nullable=True),
    sa.Column('board_recording', sa.Integer(), nullable=True),
    sa.Column('head_office', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('representative_name', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('total_employees', sa.String(), nullable=True),
    sa.Column('exchange_administration', sa.String(), nullable=True),
    sa.Column('npwp', sa.String(), nullable=True),
    sa.Column('npkp', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('listing_date', sa.String(), nullable=True),
    sa.Column('annual_dividend', sa.Float(), nullable=True),
    sa.Column('general_information', sa.String(), nullable=True),
    sa.Column('fax', sa.String(), nullable=True),
    sa.Column('founding_date', sa.String(), nullable=True),
    sa.Column('company_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_holders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('holding_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('id_field', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_holders')
    op.drop_table('profiles')
    op.drop_table('directors')
    # ### end Alembic commands ###
