"""Initial migration

Revision ID: dff1771e47f4
Revises: 
Create Date: 2023-08-10 11:55:30.922204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff1771e47f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.String(), nullable=True),
    sa.Column('commodity_name', sa.String(), nullable=True),
    sa.Column('json_data', sa.JSON(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_data')
    # ### end Alembic commands ###
